continuous deployment - budgetkey-k8s
OpenBudget/open-budget-nginx-frontend pull request #3
Opened 2018-04-12 09:53 UTC by OriHoch

2018-04-12 13:49 UTC, akariv requested changes

2018-04-12 13:49 UTC, akariv commented on .travis.yml
> +script:
why not do this using the 'deploy' section in .travis.yml
?

2018-04-12 15:02 UTC, OriHoch commented on .travis.yml
> +script:
no special reason, just used to do it like that

2018-04-23 15:18 UTC, OriHoch commented
will be handled in #4

2018-04-23 15:18 UTC, closed without merging